highlighter: pygments

encoding: utf-8
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

gems: [jekyll-paginate]
paginate: 10
paginate_path: "page:num"
layout: post
permalink: /:categories/:title
excerpt_separator: "[-----]"

# mode: dev
mode: product
url: https://hejeke.github.io/shinetou/
devurl: http://localhost:4000/
name: UniMe 
title: UniMe | Another yet unique freak is showing a freakshow
description: "Donald's personal weblog, on coding or such stuff"

my:
    displayName: UniMe
    realName: Donald.Liu
    realName_cn: 刘东钥
    jobTitle: "Python Engineer"
    contact:
        qq: 283327832
        email: mostof@126.com
        github: http://www.github.com/UniFreak
        qzone: http://744910240.qzone.qq.com
        pinterest: https://www.pinterest.com/miblah/
        tel: 15671542698
        address:
            country: China
            state: Hubei
            city: Wuhan
            distribute: Hongshan
            postcode: 450000
            cell: "XuefuJiayuan"
    skills:
        frontend: ["HTML | Markdown", "CSS | SASS", "JS | jQuery", "Bootstrap"]
        backend: ["PHP", "MySQL", "Redis", "Regex", "Laravel", "OSC"]
        tools: ["Sublime Text", "Git | Github", "Linux", "Jekyll | Liquid"]

collections:
    qqGroupGuide:
        output: true

defaults:
  - scope:
        path: ""
        type: "posts"
    values:
        excerpt: "{{ page.content }} | slice: 0 300"
  - scope:
        path: ""
        type: "qqGroupGuide"
    values:
        layout: markdownreader_bare
